# Subscribers
# 
# Under each event, you can have the following
# - arguments The array of argument to accept
# - hooks These are the classes that will subscribe to this event
subscribers:
  login_success:
    arguments: [username, password]
    hooks:
      - App\Handlers\Login\UserCookies
      - App\Handlers\Login\PlayerDetailsStore
      - App\Handlers\Login\GameProviderAuthenticate
      - App\Handlers\Login\LegacyAuthentication

  logout:
    arguments: [username]
    hooks:
      - App\Handlers\Logout\GameProviderDestroySession
      - App\Handlers\Logout\PlayerDetailsRemove
